### ISSUE TITLE
Asks for some weird password

### ISSUE THREAD

**Issue by rmoriz** [someara/kitchen-dokken#49]
when using docker-machine:

```shell

$ eval $(docker-machine env rambo)
$ kitchen setup asdf-debian

-----> Starting Kitchen (v1.13.2)
-----> Creating <asdf-debian>...
       Finished creating <asdf-debian> (0m58.49s).
-----> Converging <asdf-debian>...
       Preparing files for transfer
       Preparing dna.json
       Resolving cookbook dependencies with Berkshelf 5.1.0...
       Removing non-cookbook files before transfer
       Preparing data_bags
       Preparing secret
       Preparing validation.pem
       Preparing client.rb
       Transferring files to <asdf-debian>
root@'s password: 
```

I've no idea which password nor host dokken tries to connect to…

dokken: 1.0.5
Docker version 1.12.3, build 6b644ec
host: OSX
docker-machine host: ubuntu

remote host:

```shell

rmoriz@rambo:/home/rmoriz  $ docker ps
CONTAINER ID        IMAGE                                         COMMAND                  CREATED             STATUS              PORTS                   NAMES
73a4fd8674f8        xxx-asdf-debian:latest   "/bin/systemd"           2 minutes ago       Up 2 minutes                                xxx-asdf-debian
cb5b9dad91d0        someara/kitchen-cache:latest                  "/usr/sbin/sshd -D -p"   3 minutes ago       Up 3 minutes        0.0.0.0:32769->22/tcp   xxx-asdf-debian-data

``` 

also happens with dokken 1.0.9 and kitchen 1.14.2

**Comment by rmoriz** [comment]
nearly the same with local docker for mac on 10.12:

```
       [SSH] connection failed, retrying in 1 seconds (#<Net::SSH::Disconnect: disconnected: Too many authentication failures (2)>)
       [SSH] connection failed, retrying in 1 seconds (#<Net::SSH::Disconnect: disconnected: Too many authentication failures (2)>)
       [SSH] connection failed, retrying in 1 seconds (#<Net::SSH::Disconnect: disconnected: Too many authentication failures (2)>)
       [SSH] connection failed, retrying in 1 seconds (#<Net::SSH::Disconnect: disconnected: Too many authentication failures (2)>)
$$$$$$ [SSH] connection failed, terminating (#<Net::SSH::Disconnect: disconnected: Too many authentication failures (2)>)
```

**Comment by rmoriz** [comment]
maybe related to https://github.com/someara/kitchen-dokken/issues/50

**Comment by someara** [comment]
Fixed up in 2.0.0

**Comment by mattstratton** [comment]
I just update, and I get the same issue myself.

Versions:

`kitchen-dokken (2.0.1)`
`kitchen version: 1.14.2`

What's REALLY weird is it doesn't happen in every cookbook. I have one cookbook where it works perfectly. Another, it gives this error. I've tried blasting away the `.kitchen` directories in both, and it doesn't change the behavior.

**Comment by someara** [comment]
Have you tried cleaning out the Docker engine?

```bash
```

**Comment by someara** [comment]
Also, if you use it over a local socket (docker for mac, local linux ala Delivery/travis) it doesn't use the transport container at all anymore, instead opting to just do a bind mount of the sandbox data

**Comment by mattstratton** [comment]
I tried cleaning out the engine; still get the same issue - one of my cookbooks has the "ask for root password" issue, the other doesn't. The `.kitchen.yml` is identical for both. Weird.

**Comment by someara** [comment]
Chatted out of band... cloned matt's public repo and was able to reproduce this.
Now I have a starting point for debugging.
Investigating....

**Comment by someara** [comment]
Turns out you were missing the transport specification in your .kitchen.yml

https://github.com/mattstratton/aar_cookbook/compare/master...someara:patch-1

**Comment by mattstratton** [comment]
Oh snap. Thanks man.

**Comment by migueleite** [comment]
I still have this problem when running `kitchen converge` while using dokken.

**Comment by ramereth** [comment]
@migueleite can you please provide additional information such as versions that you're using and what you have in your `kitchen.yml`?
